service: ciacka-net-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-1
  environment:
    SENDER_EMAIL: ${ssm:contactFormSenderEmail}
    RECEIVER_EMAIL: ${ssm:contactFormReceiverEmail}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  sendMailApp:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
